before checking the missing value we should detect what is missing

in order to now what is missing fisrt we should check the validity and dataenforcement

In [24]:
import pandas as pd
import numpy as np  
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, np.nan, 30, None],
    'salary': [5000, 6000, '?', 7000],
    'gender': ['F', 'M', np.nan, 'M']
})
df

      name   age salary gender
0    Alice  25.0   5000      F
1      Bob   NaN   6000      M
2  Charlie  30.0      ?    NaN
3    David   NaN   7000      M

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     2 non-null      float64
 2   salary  4 non-null      object
 3   gender  3 non-null      object
dtypes: float64(1), object(3)
memory usage: 260.0+ bytes

In [13]:
df['age'] = df['age'].round().astype('Int64')
df['age'].dtypes
print(df['age'])

0      25
1    <NA>
2      30
3    <NA>
Name: age, dtype: Int64

In [15]:
df['salary'] = pd.to_numeric(df['salary'], errors= 'coerce')
print(df['salary'])

0    5000.0
1    6000.0
2       NaN
3    7000.0
Name: salary, dtype: float64

In [18]:
# detection now takes place
df.isnull()

    name    age  salary  gender
0  False  False   False   False
1  False   True   False   False
2  False  False    True    True
3  False   True   False   False

In [ ]:
# count missing value per columns 
missing_value_detection = df.isnull().sum()
print(missing_value_detection)

name      0
age       2
salary    1
gender    1
dtype: int64

In [19]:
# count missing values per row 
df.isnull().sum(axis=1)

0    0
1    1
2    2
3    1
dtype: int64

In [ ]:
# we can also detect row which has missing value
# 1. any missing value in row 
# 2. all missing value in row 

df[df.isnull().any(axis=1)]
df[df.isnull().all(axis=1)]

      name   age salary gender
1      Bob   NaN   6000      M
2  Charlie  30.0      ?    NaN
3    David   NaN   7000      M

In [ ]:
# we can also detect columns which has missing value
# 1. any missing value in row 
# 2. all missing value in row 

df[df.isnull().any()]
df[df.isnull().all()]