In [19]:
import pandas as pd
df  = pd.read_csv('../data/duplicated.csv')

1. Exact Duplicate 
    * records in rows is completly the same

In [20]:

# we can detect the exact duplicate using 
duplicated_check = df[df.duplicated(keep=False )]
duplicated_check

         Name            Email      Phone  Age      City  Salary  Salary_Copy
0  John Smith   john@gmail.com  123456789   25  New York   50000        50000
1  John Smith   john@gmail.com  123456789   25  New York   50000        50000
7   Sarah Lee  sarah@gmail.com  222333444   28   Houston   65000        65000
8   Sarah Lee  sarah@gmail.com  222333444   28   Houston   65000        65000

In [21]:
# we can drop them since they are exactly the same with some other columns
df = df.drop_duplicates()
df

,Name,Email,Phone,Age,City,Salary,Salary_Copy
0,John Smith,john@gmail.com,123456789,25,New York,50000,50000
2,Jon Smith,john@gmail.com,123456789,25,New York,50000,50000
3,Jane Doe,jane@gmail.com,987654321,30,Los Angeles,60000,60000
4,Jane D.,jane@gmail.com,987654321,30,Los Angeles,60000,60000
5,Michael Brown,mike@gmail.com,555123456,40,Chicago,70000,70000
6,Mike Brown,mike@gmail.com,555123456,40,Chicago,70000,70000
7,Sarah Lee,sarah@gmail.com,222333444,28,Houston,65000,65000

In [22]:
help(df.duplicated)

Help on method duplicated in module pandas.core.frame:

duplicated(
    subset: 'Hashable | Sequence[Hashable] | None' = None,
    keep: 'DropKeep' = 'first'
) -> 'Series' method of pandas.core.frame.DataFrame instance
    Return boolean Series denoting duplicate rows.

    Considering certain columns is optional.

    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns.
    keep : {'first', 'last', False}, default 'first'
        Determines which duplicates (if any) to mark.

        - ``first`` : Mark duplicates as ``True`` except for the first occurrence.
        - ``last`` : Mark duplicates as ``True`` except for the last occurrence.
        - False : Mark all duplicates as ``True``.

    Returns
    -------
    Series
        Boolean series for each duplicated rows.

    See Also
    --------
    Index.duplicated : Equivalent method on index.
    Series.duplicated : Equivalent method on Series.
    Series.drop_duplicates : Remove duplicate values from Series.
    DataFrame.drop_duplicates : Remove duplicate values from DataFrame.

    Examples
    --------
    Consider dataset containing ramen rating.

    >>> df = pd.DataFrame({
    ...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    ...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    ...     'rating': [4, 4, 3.5, 15, 5]
    ... })
    >>> df
        brand style  rating
    0  Yum Yum   cup     4.0
    1  Yum Yum   cup     4.0
    2  Indomie   cup     3.5
    3  Indomie  pack    15.0
    4  Indomie  pack     5.0

    By default, for each set of duplicated values, the first occurrence
    is set on False and all others on True.

    >>> df.duplicated()
    0    False
    1     True
    2    False
    3    False
    4    False
    dtype: bool

    By using 'last', the last occurrence of each set of duplicated values
    is set on False and all others on True.

    >>> df.duplicated(keep='last')
    0     True
    1    False
    2    False
    3    False
    4    False
    dtype: bool

    By setting ``keep`` on False, all duplicates are True.

    >>> df.duplicated(keep=False)
    0     True
    1     True
    2    False
    3    False
    4    False
    dtype: bool

    To find duplicates on specific column(s), use ``subset``.

    >>> df.duplicated(subset=['brand'])
    0    False
    1     True
    2    False
    3     True
    4     True
    dtype: bool

In [ ]:
# df.duplicated(column=['name' , 'age' ] , keep= False)
# this mean print rows which has the same name and age

2. Fuzzy Duplicate Detection
    * duplicate but not exactly but refer to same entity

Why it happens:
    1. due to typos: typing error 
    2. due to format: Abisinia and abisinia
    3. due to missing values 
    4. Abbreviations: AA and AddisAbaba
    5. short forms : leli and lelisa 


Techniques:
    1. string similarity 
        A. Levenshtein Distance: how many steps do we need to make string A same as string B [insert , delete , replace ]
        B.

In [ ]:
# when fuzzy duplicates steps to follow 
#1. Text normalization (lowercase, remove punctuation, etc.)
''' lowercasing : changing all text to lowercase to ensure that "John" and "john" are treated as the same.
    Removing spaces : eliminating leading and trailing spaces to avoid discrepancies caused by extra spaces.
    Removing punctuation : stripping out punctuation marks to prevent them from affecting the comparison.
    Standardizing formats : ensuring that dates, phone numbers, and other formatted data are consistent across entries.
    Removing stop words : eliminating common words that do not add significant meaning (e.g., "the", "and") to focus on the core content.
    Stemming or lemmatization : reducing words to their base or root form to treat different'''

# to lowercase 
df['name'] = df['name'].str.lower()
# remove spaces
df['name'] = df['name'].str.strip()
# remove punctuation
df['name'] = df['name'].str.replace(r'[^\w\s]', '', regex= True)
# \w character class that matches any word character (equivalent to [a-z,A-Z,0-9,_])
# \s character class that matches any whitespace character (equivalent to [ \t\n\r\f\v]) space , tab , newline , carriage return , form feed , vertical tab
# standardize formats
df['date'] = pd.to_datetime(df['date'], errors='coerce') # same format for all dates
df['phone'] = df['phone'].str.replace(r'\D', '', regex=True) # \D matches any non-digit character
# remove stop words
stop_words = set(['the', 'and', 'is', 'in', 'to', 'of']) # example stop words
df['name'] = df['name'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))
# stemming or lemmatization
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()
df['feedback'] = df['feedback'].apply(lambda x: ' '.join([lemma.lemmatize(word , pos='v') for word in x.split()]))  # example of lemmatization
# when not to use it :for name and address and short forms

In [ ]:
# the more accurate way is to use with the pos tag and word_tokenize

from nltk import WordNetLemmatizer
from nltk import pos_tag , word_tokenize

lemma = WordNetLemmatizer()
def pos_return(exmaple):
    if exmaple.startswith('N'):
        return 'n'
    elif exmaple.startswith('V'):
        return 'v'
    elif exmaple.startswith('J'):
        return 'a'
    elif exmaple.startswith('R'):
        return 'r'
    else:
        return 'n'

def lammatize_text(text):
    tokens = word_tokenize(text)
    pos_tag = pos_tag(tokens)

    return ' '.join([lemma.lemmatize(word , pos= pos_return(pos)) for word , pos in pos_tag])
    
df['feedback'] = df['feedback'].apply(lammatize_text)

In [ ]:
# Blocking(Reduce comparisons)

In [ ]:
# A. String similarity measures:

# here is lists of some string similarity measures that can be used to detect fuzzy duplicates:
# Damerau-Levenshtein Distance: Measures the number of edits (insertions, deletions, substitutions) required to transform one string into another.
# along with handling 
'''1. insertion : adding a character to the string (e.g., "John" -> "Johnn")
   2. deletion : removing a character from the string (e.g., "John" -> "
   3. substitution : replacing one character with another (e.g., "John" -> "Jahn")
   4. transposition : swapping two adjacent characters (e.g., "John" -> "Jhon")'''

# Jaccard Similarity: Measures the similarity between two sets of tokens by calculating the size
# of the intersection divided by the size of the union of the token sets.
# Cosine Similarity: Measures the cosine of the angle between two vectors in a multi-dimensional
# space, often used for text data represented as term frequency-inverse document frequency (TF-IDF) vectors.
# Jaro-Winkler Distance: A string comparison algorithm that gives more weight to the beginning
# of the strings, making it effective for short strings like names.
# Soundex: A phonetic algorithm that encodes words based on their pronunciation, useful for
# detecting duplicates that may have different spellings but sound similar.

In [2]:
import pandas as pd 
customers = [
    {"id": 1, "name": "John Doe", "email": "john@gmail.com", "city": "Addis Ababa"},
    {"id": 2, "name": "Jon Doe", "email": "john@gmail.com", "city": "Addis Ababa"},
    {"id": 3, "name": "Jhon Doe", "email": "john.doe@gmail.com", "city": "Addis"},
    {"id": 4, "name": "Jane Smith", "email": "jane@gmail.com", "city": "Adama"},
    {"id": 5, "name": "Jane S.", "email": "jane@gmail.com", "city": "Adama"},
    {"id": 6, "name": "Michael Brown", "email": "mike@gmail.com", "city": "Bahir Dar"},
    {"id": 7, "name": "Micheal Brown", "email": "mike@gmail.com", "city": "BahirDar"},
    {"id": 8, "name": "Mike Brown", "email": "mikeb@gmail.com", "city": "Bahir Dar"},
]
df = pd.DataFrame(customers)
df

   id           name               email         city
0   1       John Doe      john@gmail.com  Addis Ababa
1   2        Jon Doe      john@gmail.com  Addis Ababa
2   3       Jhon Doe  john.doe@gmail.com        Addis
3   4     Jane Smith      jane@gmail.com        Adama
4   5        Jane S.      jane@gmail.com        Adama
5   6  Michael Brown      mike@gmail.com    Bahir Dar
6   7  Micheal Brown      mike@gmail.com     BahirDar
7   8     Mike Brown     mikeb@gmail.com    Bahir Dar

In [5]:
the_dup = df.duplicated().sum()
print(f"Number of duplicate rows: {the_dup}")

Number of duplicate rows: 0

In [6]:
# now lets use levenshtein distance to find the fuzzy duplicates in the name column
df.columns

Index(['id', 'name', 'email', 'city'], dtype='object')

In [ ]:
def compare_value(string1 , string2):
    name_score = fuzz.ratio(string1['name'] , string2['name'])
    city_score = fuzz.ratio(string1['city'] , string2['city'])
    email_score = string1['email'] == string2['email']
    return name_score , city_score , email_score


def check_duplicate(string1 , string2):
    name_score , city_score , email_score = compare_value(string1 , string2)
    if name_score > 80 and city_score > 80 and email_score:
        return True
    else:
        return False

def find_duplicates(df):
    duplicates = []
    for i in range(len(df)):
        for j in range(i + 1, len(df)):
            if check_duplicate(df.iloc[i], df.iloc[j]):
                duplicates.append((df.iloc[i]['id'], df.iloc[j]['id']))
    return duplicates