In [1]:
import pandas as pd

In [3]:
df_1 = pd.read_csv('../../data/MCAR.csv')
df_2 = pd.read_csv('../../data/MAR.csv')

In [4]:
df_1.head()

,EmployeeID,Age,Experience,Salary,Rating,Department,Gender,Education,Region,Projects
0,E001,25,2.0,4200.0,3.8,IT,M,Bachelor,Addis,3
1,E002,29,5.0,5500.0,4.2,Marketing,F,Master,Adama,4
2,E003,31,7.0,NaN,4.5,Finance,M,Master,BahirDar,5
3,E004,26,3.0,4600.0,NaN,HR,F,Bachelor,Hawassa,2
4,E005,34,9.0,7200.0,4.8,IT,M,PhD,Addis,6

In [5]:
df_2.head()

,EmployeeID,Age,Experience,Salary,Rating,Department,Gender,Education,Region,Projects
0,E001,25,2,4200.0,NaN,IT,M,Bachelor,Addis,3
1,E002,29,5,NaN,4.2,Marketing,F,Master,Adama,4
2,E003,31,7,NaN,4.5,Marketing,M,Master,BahirDar,5
3,E004,26,3,4600.0,NaN,HR,F,Bachelor,Hawassa,2
4,E005,34,9,7200.0,4.8,IT,M,PhD,Addis,6

Indetify whether it is MCAR or MAR and Indetify which Imputation should we use model based or others

1.using corr for numeric columns

In [10]:
num_cols_1 = df_1.select_dtypes(include= 'number')
num_cols_2 = df_2.select_dtypes(include= 'number')

num_cols_1.corr()

                 Age  Experience    Salary    Rating  Projects
Age         1.000000    0.994175  0.994626  0.981462  0.958452
Experience  0.994175    1.000000  0.992263  0.978934  0.950344
Salary      0.994626    0.992263  1.000000  0.983418  0.958582
Rating      0.981462    0.978934  0.983418  1.000000  0.972723
Projects    0.958452    0.950344  0.958582  0.972723  1.000000

In [11]:
num_cols_2.corr()

                 Age  Experience    Salary    Rating  Projects
Age         1.000000    0.992675  0.996598  0.980313  0.958452
Experience  0.992675    1.000000  0.996180  0.983169  0.950871
Salary      0.996598    0.996180  1.000000  0.951734  0.966314
Rating      0.980313    0.983169  0.951734  1.000000  0.964604
Projects    0.958452    0.950871  0.966314  0.964604  1.000000